version: "3.1"
volumes:
  mongo_data:
services:
  api:
    restart: unless-stopped
    image: api:latest
    ports:
      - 4000:4000
    volumes:
      - ./api:/user/src/app
    links:
      - mongo
    command: npm watch
    tty: true
    stdin_open: true

  client:
    restart: unless-stopped
    image: client:latest
    ports:
      - 1234:1234
    volumes:
      - ./client:/usr/src/app
    links:
      - api
    command: npm start
    tty: true
    stdin_open: true

  mongo:
    restart: unless-stopped
    image: mongo:3.6.4
    volumes:
      - mongo_data:/data/db
    ports:
      - 27017:27017
